name: Deploy to Netlify

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      url:
        required: true
        type: string
      production:
        required: true
        type: boolean
    secrets:
      ACCESS_TOKEN:
        required: true
      PROD_ID:
        required: true
      STAGING_ID:
        required: true

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Site ID
        id: site_id
        run: |
          if ${{ inputs.production }}; then
            echo "SITE_ID=${{ secrets.PROD_ID }}" >> $GITHUB_ENV
          else
            echo "SITE_ID=${{ secrets.STAGING_ID }}" >> $GITHUB_ENV
          fi

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          NETLIFY_SITE_ID: ${{ env.SITE_ID }}
        run: |
          npm ci
          npm run build

      - name: Output Deployment URL
        run: echo "Deployed to ${{ inputs.url }}"
