name: Reusable Netlify Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      prod_site_id:
        required: true
        type: string
      staging_site_id:
        required: true
        type: string
      url:
        required: true
        type: string
      production:
        required: true
        type: boolean
    secrets:
      ACCESS_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.url }}

    steps:
      - uses: actions/checkout@v4

      - run: npm ci
      - run: npm run build

      - name: Select Netlify Site ID
        id: select_site_id
        run: |
          if [ "${{ inputs.production }}" = "true" ]; then
            echo "SITE_ID=${{ inputs.prod_site_id }}" >> $GITHUB_ENV
          else
            echo "SITE_ID=${{ inputs.staging_site_id }}" >> $GITHUB_ENV
          fi

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0.0
        with:
          publish-dir: ".next"
          production-deploy: ${{ inputs.production }}
          netlify-auth-token: ${{ secrets.ACCESS_TOKEN }}
          netlify-site-id: ${{ env.SITE_ID }}
        env:
          CI: true
