# .github/workflows/deploy-netlify.yml
name: Central Deploy Rule

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      site_id:
        required: true
        type: string
      url:
        required: true
        type: string
      production:
        required: true
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.url }}

    steps:
      - uses: actions/checkout@v4

      - run: npm ci
      - run: npm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0.0
        with:
          publish-dir: ".next"
          production-deploy: ${{ inputs.production }}
          netlify-auth-token: ${{ secrets.ACCESS_TOKEN }}
          netlify-site-id: ${{ inputs.site_id }}
        env:
          CI: true
